package com.alibaba.arms.mock.dao.entity;

public class DummyRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dummy_record.id
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dummy_record.content
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dummy_record.id
     *
     * @return the value of dummy_record.id
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dummy_record.id
     *
     * @param id the value for dummy_record.id
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dummy_record.content
     *
     * @return the value of dummy_record.content
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dummy_record.content
     *
     * @param content the value for dummy_record.content
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}