package com.alibaba.arms.mock.dao.mapper;

import com.alibaba.arms.mock.dao.entity.DummyRecord;
import com.alibaba.arms.mock.dao.entity.DummyRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DummyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dummy_record
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    long countByExample(DummyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dummy_record
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    int deleteByExample(DummyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dummy_record
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dummy_record
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    int insert(DummyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dummy_record
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    int insertSelective(DummyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dummy_record
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    List<DummyRecord> selectByExample(DummyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dummy_record
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    DummyRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dummy_record
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") DummyRecord record, @Param("example") DummyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dummy_record
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    int updateByExample(@Param("record") DummyRecord record, @Param("example") DummyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dummy_record
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    int updateByPrimaryKeySelective(DummyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dummy_record
     *
     * @mbg.generated Tue Jun 29 11:37:50 CST 2021
     */
    int updateByPrimaryKey(DummyRecord record);
    
    int existTable(String tableName);
    
    int createTable(String tableName);
    
    int countTable();
}