// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.0
// source: proto/b_api/b-api.proto

package b_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BRequest) Reset() {
	*x = BRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_b_api_b_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BRequest) ProtoMessage() {}

func (x *BRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_b_api_b_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BRequest.ProtoReflect.Descriptor instead.
func (*BRequest) Descriptor() ([]byte, []int) {
	return file_proto_b_api_b_api_proto_rawDescGZIP(), []int{0}
}

func (x *BRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BReply) Reset() {
	*x = BReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_b_api_b_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BReply) ProtoMessage() {}

func (x *BReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_b_api_b_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BReply.ProtoReflect.Descriptor instead.
func (*BReply) Descriptor() ([]byte, []int) {
	return file_proto_b_api_b_api_proto_rawDescGZIP(), []int{1}
}

func (x *BReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_b_api_b_api_proto protoreflect.FileDescriptor

var file_proto_b_api_b_api_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x2d,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62, 0x5f, 0x61, 0x70, 0x69,
	0x22, 0x1e, 0x0a, 0x08, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x22, 0x0a, 0x06, 0x42, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x37, 0x0a, 0x08, 0x42, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x2b, 0x0a, 0x07, 0x62, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x0f, 0x2e, 0x62, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x62,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x76, 0x0a,
	0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x61, 0x6c, 0x69, 0x79,
	0x75, 0x6e, 0x2e, 0x6d, 0x73, 0x65, 0x5f, 0x67, 0x6f, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x62,
	0x5f, 0x61, 0x70, 0x69, 0x42, 0x09, 0x42, 0x41, 0x70, 0x69, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c,
	0x69, 0x79, 0x75, 0x6e, 0x2f, 0x61, 0x6c, 0x69, 0x62, 0x61, 0x62, 0x61, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x64,
	0x65, 0x6d, 0x6f, 0x2f, 0x6d, 0x73, 0x65, 0x2d, 0x67, 0x6f, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f,
	0x62, 0x2d, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_b_api_b_api_proto_rawDescOnce sync.Once
	file_proto_b_api_b_api_proto_rawDescData = file_proto_b_api_b_api_proto_rawDesc
)

func file_proto_b_api_b_api_proto_rawDescGZIP() []byte {
	file_proto_b_api_b_api_proto_rawDescOnce.Do(func() {
		file_proto_b_api_b_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_b_api_b_api_proto_rawDescData)
	})
	return file_proto_b_api_b_api_proto_rawDescData
}

var file_proto_b_api_b_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_b_api_b_api_proto_goTypes = []interface{}{
	(*BRequest)(nil), // 0: b_api.BRequest
	(*BReply)(nil),   // 1: b_api.BReply
}
var file_proto_b_api_b_api_proto_depIdxs = []int32{
	0, // 0: b_api.BService.bMethod:input_type -> b_api.BRequest
	1, // 1: b_api.BService.bMethod:output_type -> b_api.BReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_b_api_b_api_proto_init() }
func file_proto_b_api_b_api_proto_init() {
	if File_proto_b_api_b_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_b_api_b_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_b_api_b_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_b_api_b_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_b_api_b_api_proto_goTypes,
		DependencyIndexes: file_proto_b_api_b_api_proto_depIdxs,
		MessageInfos:      file_proto_b_api_b_api_proto_msgTypes,
	}.Build()
	File_proto_b_api_b_api_proto = out.File
	file_proto_b_api_b_api_proto_rawDesc = nil
	file_proto_b_api_b_api_proto_goTypes = nil
	file_proto_b_api_b_api_proto_depIdxs = nil
}
