// Code generated by goctl. DO NOT EDIT.
// Source: demo.proto

package server

import (
	"context"

	"github.com/aliyun/alibabacloud-microservice-demo/mse-go-demo/multiframe/C/grpc/internal/logic"
	"github.com/aliyun/alibabacloud-microservice-demo/mse-go-demo/multiframe/C/grpc/internal/svc"
	"github.com/aliyun/alibabacloud-microservice-demo/mse-go-demo/multiframe/C/grpc/proto"
)

type CGreeterServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedCGreeterServer
}

func NewCGreeterServer(svcCtx *svc.ServiceContext) *CGreeterServer {
	return &CGreeterServer{
		svcCtx: svcCtx,
	}
}

// 定义一个 SayHello 一元 rpc 方法，请求体和响应体必填。
func (s *CGreeterServer) CSayHello(ctx context.Context, in *__.CSayHelloReq) (*__.CSayHelloResp, error) {
	l := logic.NewCSayHelloLogic(ctx, s.svcCtx)
	return l.CSayHello(in)
}
