apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "21"
  generation: 1
  labels:
    app: cartservice1
  name: cartservice1
  selfLink: /apis/apps/v1/namespaces/default/deployments/cartservice1
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app: cartservice1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        alicloud.service.tag: v1
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: {{ .Values.application.name.prefix}}cartservice
        msePilotAutoEnable: "on"
        msePilotCreateAppName: {{ .Values.application.name.prefix}}cartservice
      labels:
        app: cartservice1
    spec:
      containers:
      - env:
        - name: LANG
          value: C.UTF-8
        - name: JAVA_HOME
          value: /usr/lib/jvm/java-1.8-openjdk/jre
        - name: spring.cloud.nacos.discovery.server-addr
          value: {{ .Values.mse.address.springcloud}}
        - name: dubbo.registry.address
          value: {{ .Values.mse.address.dubbo}}
        - name: JAVA_TOOL_OPTIONS
          value: ' -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 '
        image: registry.cn-hangzhou.aliyuncs.com/alibabacloud-microservice-demo/cartservice:{{ .Values.images.version}}
        imagePullPolicy: Always
        name: cartservice
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
