apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  generation: 1
  labels:
    app: cartservice2
  name: cartservice2
  selfLink: /apis/apps/v1/namespaces/default/deployments/cartservice2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: cartservice2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        alicloud.service.tag: v2
        msePilotAutoEnable: "on"
        msePilotCreateAppName: cartservice
      labels:
        app: cartservice2
    spec:
      containers:
      - env:
        - name: throwException
          value: "true"
        - name: spring.cloud.nacos.discovery.server-addr
          value: {{ .Values.mse.address.springcloud}}
        - name: dubbo.registry.address
          value: {{ .Values.mse.address.dubbo}}
        image: registry.cn-hangzhou.aliyuncs.com/alibabacloud-microservice-demo/cartservice:latest
        imagePullPolicy: Always
        name: cartservice2
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
