apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "48"
  creationTimestamp: null
  generation: 1
  labels:
    app: frontend1
  name: frontend1
  selfLink: /apis/apps/v1/namespaces/default/deployments/frontend1
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app: frontend1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        alicloud.service.tag: tag1
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: {{ .Values.application.name.prefix}}frontend1
        msePilotAutoEnable: "on"
        msePilotCreateAppName: {{ .Values.application.name.prefix}}frontend
      labels:
        app: frontend1
    spec:
      containers:
      - env:
        - name: LANG
          value: C.UTF-8
        - name: JAVA_HOME
          value: /usr/lib/jvm/java-1.8-openjdk/jre
        - name: TOMCAT_ACCESSLOG_ENABLED
          value: "true"
        - name: micro.service.shutdown.wait.time
          value: "30000"
        - name: profiler.micro.service.shutdown.auto.wait.enable
          value: "false"
        - name: spring.cloud.nacos.discovery.server-addr
          value: {{ .Values.mse.address.springcloud}}
        - name: dubbo.registry.address
          value: {{ .Values.mse.address.dubbo}}
        image: registry.cn-hangzhou.aliyuncs.com/alibabacloud-microservice-demo/frontend:{{ .Values.images.version}}
        imagePullPolicy: Always
        name: frontend1
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
