apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }} 
          image: {{ .Values.frontend.image }}
          ports:
          - containerPort: {{ .Values.frontend.port }}
          env:
          - name: dubbo.registry.address
            value: "nacos://{{ .Values.nacos.host }}:{{ .Values.nacos.port }}"
          - name: spring.cloud.nacos.discovery.server-addr
            value: "{{ .Values.nacos.host }}:{{ .Values.nacos.port }}"
