apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: null
  generation: 1
  labels:
    app: loadgenerator1
  name: loadgenerator1
  selfLink: /apis/apps/v1/namespaces/default/deployments/loadgenerator
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: loadgenerator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: loadgenerator
    spec:
      containers:
      - env:
        - name: LANG
          value: C.UTF-8
        - name: GPG_KEY
          value: 0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
        - name: PYTHON_GET_PIP_URL
          value: https://github.com/pypa/get-pip/raw/404c9418e33c5031b1a9ab623168b3e8a2ed8c88/get-pip.py
        - name: PYTHON_GET_PIP_SHA256
          value: 56bb63d3cf54e7444351256f72a60f575f6d8c7f1faacffae33167afc8e7609d
        - name: FRONTEND_ADDR
          value: zuul-gateway-svc
        - name: USERS
          value: "200"
        - name: BASE_URL
          value: ""
        - name: USER_PARAM
          value: user=tag
        - name: VIEW_CART
          value: "true"
        image: registry.cn-hangzhou.aliyuncs.com/alibabacloud-microservice-demo/loadgenerator:2.0
        imagePullPolicy: IfNotPresent
        name: loadgenerator1
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
