apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
  creationTimestamp: null
  generation: 1
  labels:
    app: nacos-server
  name: nacos-server
  selfLink: /apis/apps/v1/namespaces/default/deployments/nacos-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nacos-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nacos-server
    spec:
      containers:
      - env:
        - name: MODE
          value: standalone
        - name: PREFER_HOST_MODE
          value: ip
        - name: BASE_DIR
          value: /home/nacos
        - name: CLASSPATH
          value: '.:/home/nacos/conf:'
        - name: CLUSTER_CONF
          value: /home/nacos/conf/cluster.conf
        - name: FUNCTION_MODE
          value: all
        - name: JAVA_HOME
          value: /usr/lib/jvm/java-1.8-openjdk
        - name: NACOS_USER
          value: nacos
        - name: JAVA
          value: /usr/lib/jvm/java-1.8-openjdk/bin/java
        - name: JVM_XMS
          value: 2g
        - name: JVM_XMX
          value: 2g
        - name: JVM_XMN
          value: 1g
        - name: JVM_MS
          value: 128m
        - name: JVM_MMS
          value: 320m
        - name: NACOS_DEBUG
          value: "n"
        - name: TOMCAT_ACCESSLOG_ENABLED
          value: "false"
        - name: TIME_ZONE
          value: Asia/Shanghai
        image: nacos/nacos-server:latest
        imagePullPolicy: Always
        name: nacos-server
        ports:
        - containerPort: 8848
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
