apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "21"
  generation: 1
  labels:
    app: product-mysql
  name: product-mysql
  selfLink: /apis/apps/v1/namespaces/default/deployments/product-mysql
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: product-mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: product-mysql
    spec:
      containers:
        - env:
            - name: LANG
              value: C.UTF-8
            - name: MYSQL_ROOT_PASSWORD
              value: productservice
            - name: MYSQL_DATABASE
              value: product
          image: mysql:5.6
          args:
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
          imagePullPolicy: Always
          name: product-mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
