apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "63"
  creationTimestamp: null
  generation: 1
  labels:
    app: productservice3
  name: productservice3
  selfLink: /apis/apps/v1/namespaces/default/deployments/productservice3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: productservice3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        alicloud.service.tag: tag3
      labels:
        app: productservice3
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: {{ .Values.application.name.prefix}}productservice3
        msePilotAutoEnable: "on"
        msePilotCreateAppName: {{ .Values.application.name.prefix}}productservice
    spec:
      containers:
        - env:
            - name: micro.service.shutdown.wait.time
              value: "5000"
            - name: demo_version
              value: "true"
            - name: spring.cloud.nacos.discovery.server-addr
              value: {{ .Values.mse.address.springcloud}}
            - name: dubbo.registry.address
              value: {{ .Values.mse.address.dubbo}}
            - name: JAVA_TOOL_OPTIONS
              value: ' -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 '
            - name: dubbo.consumer.check
              value: "false"
          image: registry.cn-hangzhou.aliyuncs.com/mse-hz/productservice:{{ .Values.images.version}}
          imagePullPolicy: Always
          name: productservice3
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
status: {}
