// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/aliyun/alibabacloud-microservice-demo/mse-go-demo/multiframe/C/http/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/greet1c",
				Handler: greet1cHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/greet2c",
				Handler: greet2cHandler(serverCtx),
			},
		},
	)
}
