// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.15.5
// source: api/helloworld/c_api/helloworld.proto

package c_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CGreeter_CSayHello_FullMethodName = "/helloworld.CGreeter/CSayHello"
)

// CGreeterClient is the client API for CGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type CGreeterClient interface {
	// Sends a greeting
	CSayHello(ctx context.Context, in *CHelloRequest, opts ...grpc.CallOption) (*CHelloReply, error)
}

type cGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewCGreeterClient(cc grpc.ClientConnInterface) CGreeterClient {
	return &cGreeterClient{cc}
}

func (c *cGreeterClient) CSayHello(ctx context.Context, in *CHelloRequest, opts ...grpc.CallOption) (*CHelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CHelloReply)
	err := c.cc.Invoke(ctx, CGreeter_CSayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CGreeterServer is the server API for CGreeter service.
// All implementations must embed UnimplementedCGreeterServer
// for forward compatibility.
//
// The greeting service definition.
type CGreeterServer interface {
	// Sends a greeting
	CSayHello(context.Context, *CHelloRequest) (*CHelloReply, error)
	mustEmbedUnimplementedCGreeterServer()
}

// UnimplementedCGreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCGreeterServer struct{}

func (UnimplementedCGreeterServer) CSayHello(context.Context, *CHelloRequest) (*CHelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CSayHello not implemented")
}
func (UnimplementedCGreeterServer) mustEmbedUnimplementedCGreeterServer() {}
func (UnimplementedCGreeterServer) testEmbeddedByValue()                  {}

// UnsafeCGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CGreeterServer will
// result in compilation errors.
type UnsafeCGreeterServer interface {
	mustEmbedUnimplementedCGreeterServer()
}

func RegisterCGreeterServer(s grpc.ServiceRegistrar, srv CGreeterServer) {
	// If the following call pancis, it indicates UnimplementedCGreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CGreeter_ServiceDesc, srv)
}

func _CGreeter_CSayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CGreeterServer).CSayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CGreeter_CSayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CGreeterServer).CSayHello(ctx, req.(*CHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CGreeter_ServiceDesc is the grpc.ServiceDesc for CGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.CGreeter",
	HandlerType: (*CGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CSayHello",
			Handler:    _CGreeter_CSayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/helloworld/c_api/helloworld.proto",
}
