// Code generated by goctl. DO NOT EDIT.
package types

type GreetReq struct {
	Name     string `json:"name",form:"name",query:"name"`
	CallType string `json:"callType",form:"callType",query:"callType"`
}

type GreetResp struct {
	Message   string `json:"message"`
	CallChain string `json:"CallChain"`
}
