// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.15.5
// source: api/helloworld/b_api/helloworld.proto

package b_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BGreeter_BSayHello_FullMethodName = "/helloworld.BGreeter/BSayHello"
)

// BGreeterClient is the client API for BGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type BGreeterClient interface {
	// Sends a greeting
	BSayHello(ctx context.Context, in *BHelloRequest, opts ...grpc.CallOption) (*BHelloReply, error)
}

type bGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewBGreeterClient(cc grpc.ClientConnInterface) BGreeterClient {
	return &bGreeterClient{cc}
}

func (c *bGreeterClient) BSayHello(ctx context.Context, in *BHelloRequest, opts ...grpc.CallOption) (*BHelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BHelloReply)
	err := c.cc.Invoke(ctx, BGreeter_BSayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BGreeterServer is the server API for BGreeter service.
// All implementations must embed UnimplementedBGreeterServer
// for forward compatibility.
//
// The greeting service definition.
type BGreeterServer interface {
	// Sends a greeting
	BSayHello(context.Context, *BHelloRequest) (*BHelloReply, error)
	mustEmbedUnimplementedBGreeterServer()
}

// UnimplementedBGreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBGreeterServer struct{}

func (UnimplementedBGreeterServer) BSayHello(context.Context, *BHelloRequest) (*BHelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BSayHello not implemented")
}
func (UnimplementedBGreeterServer) mustEmbedUnimplementedBGreeterServer() {}
func (UnimplementedBGreeterServer) testEmbeddedByValue()                  {}

// UnsafeBGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BGreeterServer will
// result in compilation errors.
type UnsafeBGreeterServer interface {
	mustEmbedUnimplementedBGreeterServer()
}

func RegisterBGreeterServer(s grpc.ServiceRegistrar, srv BGreeterServer) {
	// If the following call pancis, it indicates UnimplementedBGreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BGreeter_ServiceDesc, srv)
}

func _BGreeter_BSayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGreeterServer).BSayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGreeter_BSayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGreeterServer).BSayHello(ctx, req.(*BHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BGreeter_ServiceDesc is the grpc.ServiceDesc for BGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.BGreeter",
	HandlerType: (*BGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BSayHello",
			Handler:    _BGreeter_BSayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/helloworld/b_api/helloworld.proto",
}
