###
#
# 0:local->1:mysql->2:redis
#
# curl -X POST "http://127.0.0.1:9080/testcase/run?name=case1&serverUrl=http%3A%2F%2F127.0.0.1%3A9190%2F&durationSeconds=86400&qps=0&parallel=2" -H "accept: */*" -H "Content-Type: application/json" -d "{\"children\":[{\"children\":[{\"component\":\"redis\",\"method\":\"success\",\"service\":\"arms-mock-dev-2\"}],\"component\":\"mysql\",\"method\":\"success\",\"service\":\"arms-mock-dev-1\"}],\"component\":\"local\",\"method\":\"success\",\"service\":\"arms-mock-dev-0\"}"
POST http://127.0.0.1:9080/testcase/run?name=case1&serverUrl=http%3A%2F%2F127.0.0.1%3A9190%2F&durationSeconds=86400&qps=0&parallel=2
accept: */*
Content-Type: application/json

{
  "children": [
    {
      "children": [
        {
          "component": "redis",
          "method": "success",
          "service": "arms-mock-dev-2"
        }
      ],
      "component": "mysql",
      "method": "success",
      "service": "arms-mock-dev-1"
    }
  ],
  "component": "local",
  "method": "success",
  "service": "arms-mock-dev-0"
}

###

##
#
#  0:local->1:redis->2:mysql
#
#
# curl -X POST "http://127.0.0.1:9080/testcase/run?name=case0&serverUrl=http%3A%2F%2F127.0.0.1%3A9190%2F&durationSeconds=86400&qps=0&parallel=2" -H "accept: */*" -H "Content-Type: application/json" -d "{\"children\":[{\"children\":[{\"component\":\"mysql\",\"method\":\"success\",\"service\":\"arms-mock-dev-2\"}],\"component\":\"redis\",\"method\":\"success\",\"service\":\"arms-mock-dev-1\"}],\"component\":\"local\",\"method\":\"success\",\"service\":\"arms-mock-dev-0\"}"
POST http://127.0.0.1:9080/testcase/run?name=case0&serverUrl=http%3A%2F%2F127.0.0.1%3A9190%2F&durationSeconds=86400&qps=0&parallel=2
accept: */*
Content-Type: application/json

{
  "children": [
    {
      "children": [
        {
          "component": "dubbo",
          "method": "success",
          "service": "arms-mock-dev-2"
        }
      ],
      "component": "redis",
      "method": "success",
      "service": "arms-mock-dev-1"
    }
  ],
  "component": "local",
  "method": "success",
  "service": "arms-mock-dev-0"
}

###
# 2:mysql error
# curl -X POST "http://127.0.0.1:9390/trouble/make/error?fullClassName=com.alibaba.arms.mock.server.service.MysqlService&method=success" -H "accept: */*" -d ""
POST http://127.0.0.1:9390/trouble/make/error?fullClassName=com.alibaba.arms.mock.server.service.MysqlService&method=success
accept: */*
Content-Type: application/x-www-form-urlencoded

###
# 2: redis slow
# curl -X POST "http://127.0.0.1:9390/trouble/make/slow?fullClassName=com.alibaba.arms.mock.server.service.RedisService&method=success&sleepInSeconds=10" -H "accept: */*" -d ""
POST http://127.0.0.1:9390/trouble/make/slow?fullClassName=com.alibaba.arms.mock.server.service.RedisService&method=success&sleepInSeconds=10
accept: */*
Content-Type: application/x-www-form-urlencoded

###

