{{ if .Values.prometheus.enable }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spring-cloud-b
  namespace: {{ .Release.Namespace }}
spec:
  podMetricsEndpoints:
    - interval: 30s
      port: http-port
      path: /actuator/prometheus
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: spring-cloud-b

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spring-cloud-gateway
  namespace: {{ .Release.Namespace }}
spec:
  podMetricsEndpoints:
    - interval: 30s
      port: http-port
      path: /actuator/prometheus
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: spring-cloud-gateway
{{ end }}
